// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owcngmhaetmwjbesxzhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93Y25nbWhhZXRtd2piZXN4emh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTg0MDYsImV4cCI6MjA2NTQ3NDQwNn0.vyX00I6ER6J3ERYQiJBVRlLuHby6ypKwA3AHRgOHaUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);